name: Deploy Vue App to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          registry-url: "https://registry.npmjs.org/" # <--- 加上这一行，强制使用官方源

      - name: Install dependencies
        run: npm install
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/ # <--- 再加一道保险

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096" # 扩大 Node 内存限制，防止打包时内存溢出
          CI: false # 防止因为 ESLint 警告导致构建失败（Vercel/Netlify 常用技巧）

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
