name: Deploy Vue App to GitHub Pages

on:
  push:
    branches: ["main"] # 只要推送到 main 分支就触发

  workflow_dispatch: # 允许在 GitHub 网页上手动点击触发部署

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # 与你本地版本一致
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./vue-big" # Vue 打包后的目录

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
